[project]
name = "data-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adbutils>=2.9.3",
    "PyQt5>=5.15.9"
]
